#ansible-playbook -i hosts install-zabbix-agent3.yml
- hosts: amzn1 ubuntu16
  become: yes
  tasks: 
   - name: "OS Type"
     debug: msg="OS {{ansible_distribution}} {{ansible_service_mgr}}"
   
   # Amazon linux 1
   - name: yum clean all
     shell: yum clean all
     when: (ansible_distribution == "Amazon" and ansible_service_mgr == "upstart")
  
   - name: regist zabbix repo
     yum: name={{item}}
     when: (ansible_distribution == "Amazon" and ansible_service_mgr == "upstart")
     with_items:
        - http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm
 
   - name: yum install zabbix-agent
     yum: name=zabbix-agent state=present
     when: (ansible_distribution == "Amazon" and ansible_service_mgr == "upstart")
   
   # Ubuntu 16
   - name: download zabbix repo
     get_url:
        url=http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+xenial_all.deb
        dest=/tmp/zabbix-release_3.0-1+xenial_all.deb
     when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16")
   
   - name: regist zabbix repo
     apt: deb=/tmp/zabbix-release_3.0-1+xenial_all.deb
     when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16")

   - name: apt-get install zabbix-agent
     apt: name=zabbix-agent state=present update_cache=yes
     when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16")
   
   # Replace file 
   - name: replace Server in abbix_agentd.conf
     replace: 
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: '^Server=.*'
       replace: 'Server=127.0.2.32'
     notify:
        - restart zabbix-agent
 
   - name: replace ServerActive in abbix_agentd.conf
     replace: 
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: '^ServerActive=.*'
       replace: 'ServerActive=127.0.2.32'
     notify:
        - restart zabbix-agent
 
   - name: replace Hostname in abbix_agentd.conf
     replace: 
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: '^Hostname=.*'
       replace: "Hostname={{inventory_hostname}}"
     notify:
        - restart zabbix-agent
 
  handlers:
    - name: restart zabbix-agent
      service: name=zabbix-agent state=restarted
   